# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'download_manager.ui'
#
# Created: Sun Jan 10 05:00:00 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 657)
        MainWindow.setStyleSheet(_fromUtf8("margin-left:5px;"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 801, 631))
        self.tabWidget.setStyleSheet(_fromUtf8(""))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tableWidget = QtGui.QTableWidget(self.tab_2)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 791, 571))
        self.tableWidget.setBaseSize(QtCore.QSize(0, 0))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.line = QtGui.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(-10, 280, 801, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(0, 290, 791, 291))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget_5 = QtGui.QWidget(self.groupBox)
        self.layoutWidget_5.setGeometry(QtCore.QRect(0, 250, 661, 35))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.pushButton_16 = QtGui.QPushButton(self.layoutWidget_5)
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.horizontalLayout_6.addWidget(self.pushButton_16)
        self.pushButton_17 = QtGui.QPushButton(self.layoutWidget_5)
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.horizontalLayout_6.addWidget(self.pushButton_17)
        self.pushButton_18 = QtGui.QPushButton(self.layoutWidget_5)
        self.pushButton_18.setObjectName(_fromUtf8("pushButton_18"))
        self.horizontalLayout_6.addWidget(self.pushButton_18)
        self.layoutWidget_4 = QtGui.QWidget(self.groupBox)
        self.layoutWidget_4.setGeometry(QtCore.QRect(190, 20, 471, 211))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_12.setMargin(0)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.lineEdit_6 = QtGui.QLineEdit(self.layoutWidget_4)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(0, 27))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.verticalLayout_12.addWidget(self.lineEdit_6)
        self.label_67 = QtGui.QLabel(self.layoutWidget_4)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.verticalLayout_12.addWidget(self.label_67)
        self.label_68 = QtGui.QLabel(self.layoutWidget_4)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.verticalLayout_12.addWidget(self.label_68)
        self.label_69 = QtGui.QLabel(self.layoutWidget_4)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.verticalLayout_12.addWidget(self.label_69)
        self.label_70 = QtGui.QLabel(self.layoutWidget_4)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.verticalLayout_12.addWidget(self.label_70)
        self.label_71 = QtGui.QLabel(self.layoutWidget_4)
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.verticalLayout_12.addWidget(self.label_71)
        self.label_72 = QtGui.QLabel(self.layoutWidget_4)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.verticalLayout_12.addWidget(self.label_72)
        self.layoutWidget_6 = QtGui.QWidget(self.groupBox)
        self.layoutWidget_6.setGeometry(QtCore.QRect(0, 20, 141, 211))
        self.layoutWidget_6.setObjectName(_fromUtf8("layoutWidget_6"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_13.setMargin(0)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.label_73 = QtGui.QLabel(self.layoutWidget_6)
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.verticalLayout_13.addWidget(self.label_73)
        self.label_74 = QtGui.QLabel(self.layoutWidget_6)
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.verticalLayout_13.addWidget(self.label_74)
        self.label_75 = QtGui.QLabel(self.layoutWidget_6)
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.verticalLayout_13.addWidget(self.label_75)
        self.label_76 = QtGui.QLabel(self.layoutWidget_6)
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.verticalLayout_13.addWidget(self.label_76)
        self.label_77 = QtGui.QLabel(self.layoutWidget_6)
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.verticalLayout_13.addWidget(self.label_77)
        self.label_78 = QtGui.QLabel(self.layoutWidget_6)
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.verticalLayout_13.addWidget(self.label_78)
        self.label_79 = QtGui.QLabel(self.layoutWidget_6)
        self.label_79.setObjectName(_fromUtf8("label_79"))
        self.verticalLayout_13.addWidget(self.label_79)
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 0, 791, 291))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.layoutWidget_3 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(190, 20, 471, 211))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.lineEdit = QtGui.QLineEdit(self.layoutWidget_3)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 27))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.verticalLayout_3.addWidget(self.lineEdit)
        self.label_13 = QtGui.QLabel(self.layoutWidget_3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_3.addWidget(self.label_13)
        self.label_7 = QtGui.QLabel(self.layoutWidget_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_3.addWidget(self.label_7)
        self.label_8 = QtGui.QLabel(self.layoutWidget_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_3.addWidget(self.label_8)
        self.label_9 = QtGui.QLabel(self.layoutWidget_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_3.addWidget(self.label_9)
        self.label_10 = QtGui.QLabel(self.layoutWidget_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_3.addWidget(self.label_10)
        self.label_11 = QtGui.QLabel(self.layoutWidget_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_3.addWidget(self.label_11)
        self.layoutWidget = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 250, 661, 35))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton_3 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton = QtGui.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.layoutWidget_2 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 20, 141, 211))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.layoutWidget_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.label_12 = QtGui.QLabel(self.layoutWidget_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_2.addWidget(self.label_12)
        self.label_2 = QtGui.QLabel(self.layoutWidget_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.layoutWidget_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_5 = QtGui.QLabel(self.layoutWidget_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_6 = QtGui.QLabel(self.layoutWidget_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_2.addWidget(self.label_6)
        self.label_4 = QtGui.QLabel(self.layoutWidget_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_2.addWidget(self.label_4)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 33))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "File Name", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Download Link", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "File Size", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Storage Location", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "All Downloads", None))
        self.groupBox.setTitle(_translate("MainWindow", "New File 2", None))
        self.pushButton_16.setText(_translate("MainWindow", "Start", None))
        self.pushButton_17.setText(_translate("MainWindow", "Pause/Resume", None))
        self.pushButton_18.setText(_translate("MainWindow", "Cancel", None))
        self.label_67.setText(_translate("MainWindow", "0 % (0 of --MB)", None))
        self.label_68.setText(_translate("MainWindow", "New File 2", None))
        self.label_69.setText(_translate("MainWindow", "0", None))
        self.label_70.setText(_translate("MainWindow", "0", None))
        self.label_71.setText(_translate("MainWindow", "--", None))
        self.label_72.setText(_translate("MainWindow", "home/downloads", None))
        self.label_73.setText(_translate("MainWindow", "Download Link", None))
        self.label_74.setText(_translate("MainWindow", "Progress", None))
        self.label_75.setText(_translate("MainWindow", "File Name", None))
        self.label_76.setText(_translate("MainWindow", "Download Speed", None))
        self.label_77.setText(_translate("MainWindow", "Time Elapsed", None))
        self.label_78.setText(_translate("MainWindow", "Time Remaining", None))
        self.label_79.setText(_translate("MainWindow", "Storage Location", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "New File 1", None))
        self.label_13.setText(_translate("MainWindow", "0 % (0 of --MB)", None))
        self.label_7.setText(_translate("MainWindow", "New File 1", None))
        self.label_8.setText(_translate("MainWindow", "0", None))
        self.label_9.setText(_translate("MainWindow", "0", None))
        self.label_10.setText(_translate("MainWindow", "--", None))
        self.label_11.setText(_translate("MainWindow", "home/downloads", None))
        self.pushButton_3.setText(_translate("MainWindow", "Start", None))
        self.pushButton.setText(_translate("MainWindow", "Pause/Resume", None))
        self.pushButton_2.setText(_translate("MainWindow", "Cancel", None))
        self.label.setText(_translate("MainWindow", "Download Link", None))
        self.label_12.setText(_translate("MainWindow", "Progress", None))
        self.label_2.setText(_translate("MainWindow", "File Name", None))
        self.label_3.setText(_translate("MainWindow", "Download Speed", None))
        self.label_5.setText(_translate("MainWindow", "Time Elapsed", None))
        self.label_6.setText(_translate("MainWindow", "Time Remaining", None))
        self.label_4.setText(_translate("MainWindow", "Storage Location", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "New Download", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

